name: Infra - Terraform

on:
  push:
    branches: [main, develop, "feature/**", "infra/**"]
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan -var="dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}" -var="image_tag=${{ github.sha }}" -out=tfplan
        working-directory: ./infra

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra
